### ISSUE TITLE
Interactively attach to worker for debugging custom service

### ISSUE THREAD

**Issue by johncolby** [awslabs/multi-model-server#865]
Hello, Is there a way to interactively attach to a worker so I can set a breakpoint and debug my custom service code (with access to request context, data stream)? Thanks.

**Comment by vdantu** [comment]
You can debug the backend worker by stepping through. Its a python process and you can just attach the debugger to that process. We don't have a documentation for this yet. You would have to set `debug=true` in config.properties before you start MMS and then start the IDE/debugger with the backend worker process. 

We might need a detailed document of how to debug. In the mean time, what is the issue that you are facing? If you are not able to figure out how to start the backend worker with your debugger, do let us know where you are stuck :)

P.S: I use PyCharm IDE to debug both frontend and backend.

**Comment by johncolby** [comment]
Perfect, works like a *charm*.

1. Add `debug=true` to `config.properties`.
1. Start `mxnet-model-server`, which now in debug mode will start the frontend but not the backend workers.
1. Start a backend worker manually in debugger, something like `python /path/to/model_service_worker.py --sock-type unix --sock-name /tmp/.mms.sock.9000`. Working directory should be in the appropriate model directory.
1. Set breakpoints, etc. in custom service code.
1. Submit test requests to mms endpoint, e.g. `curl -X POST ...`
1. Debug...

Thanks!!

**Comment by vdantu** [comment]
👍 

Would you want to contribute to the documentation?
