### ISSUE TITLE
Some docs still contain "Model Server for Apache MXNet (MMS)"

### ISSUE THREAD

**Issue by vdantu** [awslabs/multi-model-server#870]
Main README references MMS as "Model Server for Apache MXNet (MMS)". Some documents might still be calling MMS as "Model Server for Apache MXNet", which might need to be changed.

**Comment by alexwong** [comment]
Well, I missed this one (along w/ others). https://github.com/awslabs/multi-model-server/pull/872

**Comment by alexwong** [comment]
The rest of the renaming mainly involves docker containers which haven't been updated to reflect the new name. Will have a larger PR after this to rename everything once we have them.

**Comment by alexwong** [comment]
This finishes the name change. https://github.com/awslabs/multi-model-server/pull/874
