### ISSUE TITLE
Serve multiple models Pytorch GPU memory problem

### ISSUE THREAD

**Issue by netpcvnn** [awslabs/multi-model-server#880]
Hi all,

I would like to serve multiple models but look like each model (service) consumes a lot of memory for example (Model size 70MB but it consumes about 1GB GPU memory).
Do we have any ways to reduce the GPU memory?

**Comment by vdantu** [comment]
@netpcvnn 
There is an experimental feature called [`preload_model`](https://github.com/awslabs/multi-model-server/blob/master/docker/config.properties#L6). This enables model server to have a single copy of model on the host. You could try that and see how that works for you. 

```
pip install --pre mxnet-model-server
```

**Comment by netpcvnn** [comment]
Thanks @vdantu 
I have tried use preload_model but I haven't seen the difference. So each model occupied about 1 GB GPU memory that is independent on model size.
Actually, I dont understand much about preload_model feature and how it works.

**Comment by vdantu** [comment]
preload_model = true? what version of MMS are you running?

**Comment by netpcvnn** [comment]
Yes, I have tried the config.properties with `preload_model=true`. 
The version of  MMS I used:  1.0.8 with pip install.
My config file as follow and GPU memory usage with 3 models:
![Screenshot from 2019-11-28 09-00-58](https://user-images.githubusercontent.com/1009395/69771118-3fcbca00-11be-11ea-893b-ea8cb56ca6e9.png)
![Screenshot from 2019-11-28 08-58-49](https://user-images.githubusercontent.com/1009395/69771126-45c1ab00-11be-11ea-8fa3-f15aaec24f7f.png)

**Comment by vdantu** [comment]
@netpcvnn : I don't think this feature was in 1.0.8. It must have gone in with the latest version of MMS 

@alexwong : Please feel free to correct me :)

**Comment by netpcvnn** [comment]
Thanks for your helps.
I have checked the MMS version again. The version is 1.0.8.1.

**Comment by vdantu** [comment]
@netpcvnn : If its not working with 1.0.8.1, could you try once with the pre release? 

`
pip install --pre mxnet-model-server
`

**Comment by netpcvnn** [comment]
Hi, 
I tried installing pre-release version. The version now is 1.0.9b20191115.
But I haven't seen the difference. The GPU memory is still the same.

**Comment by vdantu** [comment]
ohh. I might have missed the bigger question. This feature only works for CPUs not GPUs. For GPUs I don't know of any way to optimize for memory.

**Comment by netpcvnn** [comment]
Thanks. But looks like it's pytorch problem when loading models to GPU.
