### ISSUE TITLE
autoscaling with --model-store

### ISSUE THREAD

**Issue by xxxpsyduck** [awslabs/multi-model-server#903]
It seems like autoscale only works with `--models` but not `--model-store`

**Comment by xxxpsyduck** [comment]
When using `--model-store`, I'm forced to use Management API to register and scale model.

**Comment by vdantu** [comment]
when you configure `--model-store` try to use [load_models=ALL](https://github.com/awslabs/multi-model-server/blob/master/docker/config.properties#L3) in config.properties .. That should technically load all the models in the `--model-store` and scale it to num-gpu's or num-cpu's

**Comment by vdantu** [comment]
@xxxpsyduck : Please do let us know if this works for you :)

**Comment by xxxpsyduck** [comment]
@vdantu It did registered all the models but there is 0 worker of them. I still need to use management API to init worker

**Comment by xxxpsyduck** [comment]
I see that there is a option `default_workers_per_model` in config.properties. But I want mms to autoscale. Any suggesstion?

**Comment by xxxpsyduck** [comment]
One more dumb question: in the case of loading multiple models, how does autoscaling work?

**Comment by xxxpsyduck** [comment]
it works! thanks!
